### ISSUE TITLE
isEligibleForHandoff

### ISSUE THREAD

**Issue by favnec5** [JulianSanio/cordova-plugin-siri-shortcuts#1]
Hello,
When the apple Carplay is connected to the phone, Siri does not want execute commands.
I am searching for other options in shotcuts. I find : " isEligibleForHandoff "
(https://developer.apple.com/documentation/foundation/nsuseractivity/1410971-iseligibleforhandoff)

Could you add the option "iseligibleforhandoff" in the Present function ?
I hope that it solves this kind of problems.

best reguards
Thomas

**Comment by JulianSanio** [comment]
Hi Thomas,

thanks for your request. Since I don't have a car with Carplay, I'm not able to test this issue properly. After having a quick look at the documentation, I could find the following additional flags:
* `isEligibleForHandoff` --> The default value of this property is _true_.
* `isEligibleForPublicIndexing` --> The default value of this property is _false_.

My implementation doesn't set any of them, so default values should be active. This means `isEligibleForHandoff` is already set to _true_. If you want to try out different configurations, you could open _SiriShortcuts.m_ in Xcode and set flags as preferred in method _createUserActivityWithOptions_.

Please share your results and I will add them to shortcut options of this plugin.

Best, 
Julian

**Comment by favnec5** [comment]
Hello Julian
Your'r right, no effects to the carPlay with tests.
Sorry, i had not seen "true" default value.
It would have been too simple !
I guess the problem is that app is not authorised by the carplay system.
I think no solution at the moment.

Best reguards
Thomas
